Apparently this is not enough, because: s rc/libutil/serialise.cc:161:2: error: #error Coroutines are broken in this version of Boost!  #error Coroutines are broken in this version of Boost!
Which effectively blocks Nix 2.1.3 + Libreoffice (and other software).

Revert "nix-2.3.1-r1: boost-1.6.5 should be enough because nix itselfs builds with boost 1.6"

This reverts commit 903a46167471054025d29d630b0fa4284a532915.